version: '3.7'

services:

  wordpress-woocommerce:
    image: fchipi/wordpress-woocommerce-xdebug:v1.1.0
    restart: always
    ports:
      - 8081:80
      - 8443:443
    environment:
      WORDPRESS_DB_HOST: db-woocommerce
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
      XDEBUG_CONFIG: remote_host=host.docker.internal
    volumes: 
      - ./html:/var/www/html/

  db-woocommerce:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_RANDOM_ROOT_PASSWORD: '1'